name: ML Pipeline CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  preprocess:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Pull data (DVC)
        run: |
          pip install dvc[gs,s3]
          dvc pull || echo "No DVC data"
      - name: Run Preprocessing
        run: python preprocess.py

  train:
    runs-on: ubuntu-latest
    needs: preprocess
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Train Model
        run: python train.py

  test:
    runs-on: ubuntu-latest
    needs: train
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"
      - name: Install dependencies
        run: pip install -r requirements.txt pytest
      - name: Run Tests
        run: pytest -v
