name: CI - Streamlit App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Set up Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      # 3. Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      # 4. Lint the code (optional but recommended)
      - name: Run linter
        run: |
          pip install flake8
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=88 --statistics

      # 5. Run tests (if you have any)
      - name: Run tests
        run: |
          pip install pytest
          pytest || echo "⚠️ No tests found — skipping"

      # 6. Check Streamlit app syntax
      - name: Validate Streamlit app
        run: |
          streamlit run app/streamlit_app.py --server.headless true & sleep 5
          pkill streamlit
