name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install dvc[all]  # Only if you use DVC

  dvc_pull:
    needs: setup
    runs-on: ubuntu-latest
    if: ${{ github.event_name != 'pull_request' }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install DVC
        run: pip install dvc[all]

      - name: Pull DVC data/models
        run: dvc pull

  test:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run tests
        run: pytest tests/ --maxfail=1 --disable-warnings -q

  lint:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install flake8
        run: pip install flake8

      - name: Run lint
        run: flake8 src/

  build:
    needs: [test, lint]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Build package
        run: |
          python setup.py sdist bdist_wheel
